import type {
  ActivityEntry,
  Decision,
  DocumentItem,
  EventItem,
  TrackerItem,
} from "./types"

export const seedTracker: TrackerItem[] = [
  {
    id: "t1",
    deliverable: "Finalize GenAssembly venue booking",
    owner: "Rhea Santos",
    reviewer: "Miguel Cruz",
    targetDate: "2026-08-28",
    status: "In Progress",
  },
  {
    id: "t2",
    deliverable: "Sponsorship deck for TechSummit",
    owner: "Aaron Dela Peña",
    reviewer: "Rhea Santos",
    targetDate: "2026-08-26",
    status: "Blocked",
    blockers: "Waiting on final logo assets from Graphics team",
  },
  {
    id: "t3",
    deliverable: "Membership drive registration form",
    owner: "Kim Lorenzo",
    reviewer: "Aaron Dela Peña",
    targetDate: "2026-09-04",
    status: "Not Started",
  },
  {
    id: "t4",
    deliverable: "Q1 financial report draft",
    owner: "Miguel Cruz",
    reviewer: "Rhea Santos",
    targetDate: "2026-08-24",
    status: "Done",
  },
  {
    id: "t5",
    deliverable: "Update org website officer roster",
    owner: "Kim Lorenzo",
    reviewer: "Miguel Cruz",
    targetDate: "2026-08-30",
    status: "In Progress",
  },
]

export const seedEvents: EventItem[] = [
  {
    id: "e1",
    name: "General Assembly 2026",
    department: "Operations",
    stage: "Final Approval",
    owner: "Rhea Santos",
    targetDate: "2026-09-15",
    notes: "Main welcome event for new members. Awaiting President sign-off on program flow and budget.",
    escalations: [
      { id: "esc-e1a", reason: "Costs money not budgeted", resolved: false },
    ],
  },
  {
    id: "e2",
    name: "TechSummit: AI & You",
    department: "Technology",
    stage: "Marketing Plan",
    owner: "Aaron Dela Peña",
    targetDate: "2026-10-20",
    notes: "Flagship technical seminar with external speaker from a partner company.",
    escalations: [
      { id: "esc-e2a", reason: "Involves outside party", resolved: false },
    ],
  },
  {
    id: "e3",
    name: "Membership Recruitment Week",
    department: "Membership",
    stage: "Logistics/GPOA",
    owner: "Kim Lorenzo",
    targetDate: "2026-09-29",
    notes: "Week-long booth activation across campus.",
    escalations: [],
  },
  {
    id: "e4",
    name: "Coding Bootcamp Series",
    department: "Technology",
    stage: "Concept",
    owner: "Aaron Dela Peña",
    targetDate: "2026-11-10",
    notes: "Beginner-friendly weekend workshops. Still scoping topics and mentors.",
    escalations: [],
  },
  {
    id: "e5",
    name: "Founding Anniversary Night",
    department: "Marketing",
    stage: "Internal Review",
    owner: "Rhea Santos",
    targetDate: "2026-09-05",
    notes: "Formal celebration. Lead time deadline is tight.",
    escalations: [
      { id: "esc-e5a", reason: "Deadline at risk", resolved: false },
    ],
  },
  {
    id: "e6",
    name: "Intramurals Booth",
    department: "Graphics",
    stage: "Execution",
    owner: "Kim Lorenzo",
    targetDate: "2026-08-27",
    notes: "Materials printed, volunteers scheduled.",
    escalations: [],
  },
]

export const seedDocuments: DocumentItem[] = [
  {
    id: "d1",
    title: "Constitution & Bylaws Amendment 2026",
    type: "Internal Matters",
    stage: "Up for Approval",
    preparedBy: "Miguel Cruz",
    reviewedBy: "Rhea Santos",
    versionDate: "2026-08-20",
    escalations: [
      { id: "esc-d1a", reason: "Touches CBL/public image", resolved: false },
    ],
  },
  {
    id: "d2",
    title: "General Plan of Action FY2026-2027",
    type: "Internal Matters",
    stage: "Reviewing",
    preparedBy: "Rhea Santos",
    versionDate: "2026-08-22",
    escalations: [],
  },
  {
    id: "d3",
    title: "New Member Orientation Handbook",
    type: "Internal Matters",
    stage: "Reviewed",
    preparedBy: "Kim Lorenzo",
    reviewedBy: "Aaron Dela Peña",
    versionDate: "2026-08-18",
    escalations: [],
  },
  {
    id: "d4",
    title: "TechSummit Registration Announcement",
    type: "Event",
    stage: "Draft",
    preparedBy: "Aaron Dela Peña",
    versionDate: "2026-08-23",
    escalations: [],
  },
  {
    id: "d5",
    title: "FY2025 Annual Accomplishment Report",
    type: "Others",
    stage: "Approved",
    preparedBy: "Miguel Cruz",
    reviewedBy: "Rhea Santos",
    approvedBy: "Rhea Santos",
    versionDate: "2026-06-30",
    escalations: [],
  },
]

export const seedDecisions: Decision[] = [
  {
    id: "dec1",
    description: "Approved partnership with external sponsor for TechSummit",
    tier: 3,
    decidedBy: "Rhea Santos",
    date: "2026-08-21",
    reason:
      "Sponsor covers venue and speaker fees; involves an outside party and affects org public image, requiring President-level approval.",
    escalations: [
      { id: "esc-dec1a", reason: "Involves outside party", resolved: true },
    ],
  },
  {
    id: "dec2",
    description: "Allocated additional PHP 8,000 to General Assembly catering",
    tier: 2,
    decidedBy: "Miguel Cruz",
    date: "2026-08-19",
    reason: "Headcount rose above projection; budget line adjusted from contingency fund.",
    escalations: [],
  },
  {
    id: "dec3",
    description: "Moved weekly officer sync from Monday to Wednesday",
    tier: 1,
    decidedBy: "Rhea Santos",
    date: "2026-08-15",
    reason: "",
    escalations: [],
  },
]

export const seedActivity: ActivityEntry[] = [
  {
    id: "a1",
    timestamp: "2026-08-23T14:20:00",
    actor: "Aaron Dela Peña",
    message: "moved TechSummit: AI & You to Marketing Plan",
    kind: "stage",
  },
  {
    id: "a2",
    timestamp: "2026-08-22T10:05:00",
    actor: "Rhea Santos",
    message: "submitted General Plan of Action FY2026-2027 for Reviewing",
    kind: "stage",
  },
  {
    id: "a3",
    timestamp: "2026-08-21T16:40:00",
    actor: "Rhea Santos",
    message: "logged a Tier 3 decision: external sponsor partnership",
    kind: "decision",
  },
  {
    id: "a4",
    timestamp: "2026-08-21T09:15:00",
    actor: "System",
    message: "flagged General Assembly 2026: Costs money not budgeted",
    kind: "escalation",
  },
  {
    id: "a5",
    timestamp: "2026-08-20T11:30:00",
    actor: "Miguel Cruz",
    message: "marked Q1 financial report draft as Done",
    kind: "status",
  },
]
